### ISSUE TITLE
Null injection error

### ISSUE THREAD

**Issue by nagendranice** [robisim74/angular-l10n#276]
ERROR NullInjectorError: StaticInjectorError(AppModule)[ContactService -> Http]: 
  StaticInjectorError(Platform: core)[ContactService -> Http]: 
    NullInjectorError: No provider for Http!
    at NullInjector.get (http://localhost:4200/vendor.js:36417:27)
    at resolveToken (http://localhost:4200/vendor.js:51335:24)
    at tryResolveToken (http://localhost:4200/vendor.js:51261:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:51111:20)
    at resolveToken (http://localhost:4200/vendor.js:51335:24)
    at tryResolveToken (http://localhost:4200/vendor.js:51261:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:51111:20)
    at resolveNgModuleDep (http://localhost:4200/vendor.js:62298:29)
    at NgModuleRef_.get (http://localhost:4200/vendor.js:63364:16)
    at resolveDep (http://localhost:4200/vendor.js:63895:45)

**Comment by robisim74** [comment]
@nagendranice Are you importing _HttpClientModule_ in your app?

If you are importing it, please provide more info, and explain how that error is related to this library.
