### ISSUE TITLE
build errror

### ISSUE THREAD

**Issue by surfspiders** [robisim74/angular-l10n#38]
I tried to build with 'npm run build' ('npm start' does not work) your sample project with latest version (node 7.2.0 and npm 4.0.2) but I get following error. What do I wrong?

Start building...
Start TSLint
TSLint completed
Start AoT compilation
ngc -p tsconfig-build.json
Error: Metadata version mismatch for module C:/tmp/angular2localization/src/services/locale.service.ts, found version 2, expected 1
    at StaticReflector.getModuleMetadata (C:\tmp\angular2localization\node_modules\@angular\compiler-cli\src\static_reflector.js:500:23)
    at C:\tmp\angular2localization\node_modules\@angular\compiler-cli\src\codegen.js:122:46
    at Array.forEach (native)
    at extractProgramSymbols (C:\tmp\angular2localization\node_modules\@angular\compiler-cli\src\codegen.js:120:10)
    at CodeGenerator.codegen (C:\tmp\angular2localization\node_modules\@angular\compiler-cli\src\codegen.js:57:29)
    at codegen (C:\tmp\angular2localization\node_modules\@angular\compiler-cli\src\main.js:7:81)
    at Object.main (C:\tmp\angular2localization\node_modules\@angular\tsc-wrapped\src\main.js:37:16)
    at Object.<anonymous> (C:\tmp\angular2localization\node_modules\@angular\compiler-cli\src\main.js:16:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
Compilation failed

**Comment by robisim74** [comment]
Hi,

for `npm start` you have to wait webpack build bundles.

The error on `npm run build` seems an Angular problem:  https://github.com/angular/angular/issues/13057

I tried to update Angular packages to 2.2.3 and it works (but when I created the sample, it worked also with 2.2.0...).

Tonight I'll update the sample app.

Greetings,

Roberto
